// /* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

// import {
//     faAngleDown,
//     faAngleRight,faAlignJustify,
//     faArrowLeft,
//     faBars,
//     faBookOpen,
//     faChartArea,
//     faChartBar,
//     faChartPie,
//     faCheck,
//     faChevronDown,
//     faChevronRight,
//     faChevronUp,
//     faCircle,
//     faColumns,
//     faDollarSign,
//     faExclamation,
//     faExclamationTriangle,
//     faFlag,
//     faLongArrowAltRight,
//     faMousePointer,
//     faPercentage,
//     faPlus,faCog,
//     faPlusCircle,
//     faSearch,
//     faTable,faBan,faObjectGroup,
//     faTachometerAlt,
//     faTag,faFilter,faPen,faUnlockAlt,faBarcode,
//     faTimes,faEye,faEyeSlash,faSignInAlt,faKey,faStore,faHandshake,faWrench,faCalculator,faChartLine,faDotCircle,faWarehouse,faCalendarAlt,
//     faUser,faPlusSquare,faTrashAlt, faTrash,faSlidersH,faEdit,faBook,faMinusCircle,faPrint,faFileInvoice,faFileInvoiceDollar,faCircleNotch
// } from '@fortawesome/free-solid-svg-icons';

// export const fontAwesomeSolidIcons = {
//     faAngleDown,
//     faAngleRight,
//     faArrowLeft,
//     faBars,
//     faBookOpen,
//     faChartArea,
//     faChartBar,
//     faChartPie,faAlignJustify,
//     faCheck,
//     faChevronDown,
//     faChevronRight,
//     faChevronUp,
//     faCircle,
//     faColumns,
//     faDollarSign,
//     faExclamation,
//     faExclamationTriangle,
//     faFlag,
//     faLongArrowAltRight,
//     faMousePointer,
//     faPercentage,
//     faPlus,
//     faPlusCircle,
//     faSearch,
//     faTable,
//     faTachometerAlt,faCog,
//     faTag,faBan,faObjectGroup,
//     faTimes,faPen,faUnlockAlt,faBarcode,
//     faUser,faEye,faEyeSlash,faSignInAlt,faKey,faStore,faHandshake,faWrench,faCalculator,faChartLine,faDotCircle,faWarehouse,faCalendarAlt,
//     faPlusSquare,faTrashAlt,faTrash,faSlidersH,faEdit,faBook,faMinusCircle,faFilter,faPrint,faFileInvoice,faFileInvoiceDollar,faCircleNotch
// };
